name: Build Example OS Images
on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-matrix:
    strategy:
      matrix:
        include:
          - image: ubuntu
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - image: rbpi
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          # If you have images that do not require a platform flag, set platform to an empty string:
          # - image: some-other-image
          #   platform: ""
          #   runs-on: ubuntu-latest
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          # Check if a platform was set; if so, add it to the build command.
          if [ -n "${{ matrix.platform }}" ]; then
            docker build --platform ${{ matrix.platform }} -t example-${{ matrix.image }}-os examples/${{ matrix.image }}
            docker run --rm --platform ${{ matrix.platform }} -v /var/run/docker.sock:/var/run/docker.sock --entrypoint /bin/sh -v /build:/output ghcr.io/rancher/elemental-toolkit/elemental-cli:v2.2.0 -c "elemental build-disk --squash-no-compression --system example-${{ matrix.image }}-os --config-dir /config --local --output /build --expandable --debug -n ${{ matrix.image }} && mv /build/${{ matrix.image }}.raw /output/"
          else
            docker build -t example-${{ matrix.image }}-os examples/${{ matrix.image }}
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --entrypoint /bin/sh -v /build:/output ghcr.io/rancher/elemental-toolkit/elemental-cli:v2.2.0 -c "elemental build-disk --squash-no-compression --system example-${{ matrix.image }}-os --config-dir /config --local --output /build --expandable --debug -n ${{ matrix.image }} && mv /build/${{ matrix.image }}.raw /output/"
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: example-${{ matrix.image }}-os
          path: /build/${{ matrix.image }}.raw
          compression-level: 9
