name: Build
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build-matrix:
    # Create a matrix that includes both 'image' and 'platform'
    strategy:
      matrix:
        include:
          - image: ubuntu
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          - image: rbpi
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
          # If you have images that do not require a platform flag, set platform to an empty string:
          # - image: some-other-image
          #   platform: ""
          #   runs-on: ubuntu-latest
      fail-fast: false

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # Check if a platform was set; if so, add it to the build command.
          if [ -n "${{ matrix.platform }}" ]; then
            docker build \
              --platform ${{ matrix.platform }} \
              -t ghcr.io/${{ steps.registry_case.outputs.lowercase }}/${{ matrix.image }}-os:latest \
              images/${{ matrix.image }}
          else
            docker build \
              -t ghcr.io/${{ steps.registry_case.outputs.lowercase }}/${{ matrix.image }}-os:latest \
              images/${{ matrix.image }}
          fi

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.registry_case.outputs.lowercase }}/${{ matrix.image }}-os:latest
